"""Compile the learned LR capability-gate advisor (advisor_model_v2.joblib) into pure C.

The trained model is a sklearn Pipeline:
    ColumnTransformer[ char_wb TfidfVectorizer ngram(3,5) on "text"
                       + passthrough numeric (tainted, private, tier) ]
    -> LogisticRegression

This exporter extracts the vocabulary + idf_ and the LR coef_/intercept_ and emits a
self-contained src/cap_model.c + include/cap_model.h exposing:

    double cap_model_score(const char *text, int tainted, int private, int tier);  // sigmoid prob
    int    cap_model_deny (const char *text, int tainted, int private, int tier);  // score >= 0.5

The C reproduces the pipeline EXACTLY:
  * char_wb tokenization: lowercase, split on whitespace, pad each word with a leading and
    trailing space, then char n-grams for n in 3..5 over CODE POINTS (UTF-8 aware), with
    sklearn's short-word/edge break semantics.
  * tf-idf: per-ngram value = tf * idf; the text block is L2-normalized (norm='l2') before
    the LR dot-product — reproduced via norm = sqrt(sum (tf*idf)^2).
  * score = (1/norm) * sum_j coef_text[j]*idf[j]*tf_j  +  coef_num . [tainted,private,tier]
            + intercept ; return sigmoid(score).

Vocabulary is emitted as an exact string table indexed by a runtime-built open-addressing
hash (feature hashing into a fixed-size array, collision-safe via string compare).

    python3.12 export_to_c.py            # emits the C, then verifies parity vs the joblib model
"""
import glob
import json
import os
import subprocess
import sys
import tempfile

import joblib
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
MODEL_PATH = os.path.join(HERE, "advisor_model_v2.joblib")
C_OUT = os.path.join(REPO, "src", "cap_model.c")
H_OUT = os.path.join(REPO, "include", "cap_model.h")


def _tier_code(t):
    return {"untrusted": 0, "standard": 1, "trusted": 2}.get(t, 1)


def c_escape(s: str) -> str:
    """Escape a vocab n-gram (a Python str) into a byte-exact C string literal.

    char_wb n-grams are code-point strings; we emit their UTF-8 bytes. Printable ASCII
    (except " and \\) is emitted verbatim; every other byte becomes a 3-digit octal escape
    (unambiguous, unlike \\x which is greedy)."""
    out = []
    for b in s.encode("utf-8"):
        if b == 0x22:      # "
            out.append('\\"')
        elif b == 0x5C:    # backslash
            out.append("\\\\")
        elif 0x20 <= b <= 0x7E:
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    return "".join(out)


def main():
    model = joblib.load(MODEL_PATH)
    ct = model.named_steps["feat"]
    clf = model.named_steps["clf"]
    tfidf = ct.named_transformers_["text"]

    assert tfidf.analyzer == "char_wb", tfidf.analyzer
    assert tuple(tfidf.ngram_range) == (3, 5), tfidf.ngram_range
    assert tfidf.norm == "l2" and tfidf.use_idf and not tfidf.sublinear_tf and not tfidf.binary
    assert bool(tfidf.lowercase)

    vocab = tfidf.vocabulary_              # ngram -> column index
    idf = tfidf.idf_.astype(np.float64)
    n_text = len(vocab)
    assert idf.shape[0] == n_text

    coef = clf.coef_.ravel().astype(np.float64)
    intercept = float(clf.intercept_[0])
    assert coef.shape[0] == n_text + 3, (coef.shape, n_text)

    # column-ordered arrays
    ngrams = [None] * n_text
    for ng, col in vocab.items():
        ngrams[col] = ng
    assert all(g is not None for g in ngrams)

    w = coef[:n_text] * idf                # per-ngram score weight = coef * idf
    d = idf                                # per-ngram idf (for the L2 norm)
    coef_tainted, coef_private, coef_tier = coef[n_text], coef[n_text + 1], coef[n_text + 2]

    # ── emit header ──
    with open(H_OUT, "w") as fh:
        fh.write(
            "#ifndef DSCO_CAP_MODEL_H\n#define DSCO_CAP_MODEL_H\n\n"
            "/* AUTO-GENERATED by environments/capability_gate/ml/export_to_c.py — DO NOT EDIT.\n"
            " * Pure-C compilation of the learned LR capability-gate advisor\n"
            " * (advisor_model_v2.joblib): char_wb(3,5) tf-idf + numeric -> logistic regression. */\n\n"
            "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
            "/* Sigmoid probability that the tool call should be DENIED (exfil-risk), in [0,1].\n"
            " * `text` is \"<tool> <input_json>\"; tainted/private are 0/1 session flags; tier is\n"
            " * 0=untrusted,1=standard,2=trusted. Reproduces the sklearn pipeline bit-for-bit. */\n"
            "double cap_model_score(const char *text, int tainted, int private, int tier);\n\n"
            "/* 1 iff cap_model_score(...) >= 0.5. */\n"
            "int cap_model_deny(const char *text, int tainted, int private, int tier);\n\n"
            "#ifdef __cplusplus\n}\n#endif\n\n#endif /* DSCO_CAP_MODEL_H */\n"
        )

    # ── emit implementation ──
    with open(C_OUT, "w") as fh:
        wr = fh.write
        wr("/* AUTO-GENERATED by environments/capability_gate/ml/export_to_c.py — DO NOT EDIT.\n"
           " * Pure-C compilation of the learned LR capability-gate advisor. See the exporter\n"
           " * for the exact reproduction of the sklearn char_wb(3,5) tf-idf + LR pipeline. */\n")
        wr('#include "cap_model.h"\n')
        wr("#include <stdlib.h>\n#include <string.h>\n#include <math.h>\n#include <ctype.h>\n#include <stdint.h>\n\n")
        wr("#define CAPM_N %d  /* vocabulary size */\n\n" % n_text)
        wr("static const double CAPM_INTERCEPT = %.17g;\n" % intercept)
        wr("static const double CAPM_COEF_TAINTED = %.17g;\n" % coef_tainted)
        wr("static const double CAPM_COEF_PRIVATE = %.17g;\n" % coef_private)
        wr("static const double CAPM_COEF_TIER    = %.17g;\n\n" % coef_tier)

        # n-gram string table
        wr("static const char *const CAPM_NG[CAPM_N] = {\n")
        for i in range(n_text):
            wr('  "%s",\n' % c_escape(ngrams[i]))
        wr("};\n\n")
        # weight = coef*idf  and  idf arrays (float is ample; parity verified below)
        wr("static const float CAPM_W[CAPM_N] = {\n")
        for i in range(0, n_text, 8):
            wr("  " + ",".join("%.9gf" % w[j] for j in range(i, min(i + 8, n_text))) + ",\n")
        wr("};\n\n")
        wr("static const float CAPM_IDF[CAPM_N] = {\n")
        for i in range(0, n_text, 8):
            wr("  " + ",".join("%.9gf" % d[j] for j in range(i, min(i + 8, n_text))) + ",\n")
        wr("};\n\n")

        # runtime open-addressing hash: ngram bytes -> column index (exact, collision-safe)
        cap = 1
        while cap < n_text * 2:
            cap <<= 1
        wr("#define CAPM_HCAP %d  /* power-of-two hash capacity */\n" % cap)
        wr(r"""
static int   CAPM_HASH[CAPM_HCAP];
static int   capm_ready = 0;

static uint32_t capm_fnv(const char *s, size_t n) {
    uint32_t h = 2166136261u;
    for (size_t i = 0; i < n; i++) { h ^= (unsigned char)s[i]; h *= 16777619u; }
    return h;
}

static void capm_init(void) {
    for (int i = 0; i < CAPM_HCAP; i++) CAPM_HASH[i] = -1;
    for (int i = 0; i < CAPM_N; i++) {
        const char *g = CAPM_NG[i];
        uint32_t h = capm_fnv(g, strlen(g)) & (CAPM_HCAP - 1);
        while (CAPM_HASH[h] != -1) h = (h + 1) & (CAPM_HCAP - 1);
        CAPM_HASH[h] = i;
    }
    capm_ready = 1;
}

/* exact lookup of an n-gram (bytes [s, s+n)) -> column index, or -1 */
static int capm_lookup(const char *s, size_t n) {
    uint32_t h = capm_fnv(s, n) & (CAPM_HCAP - 1);
    for (;;) {
        int idx = CAPM_HASH[h];
        if (idx == -1) return -1;
        const char *g = CAPM_NG[idx];
        if (strlen(g) == n && memcmp(g, s, n) == 0) return idx;
        h = (h + 1) & (CAPM_HCAP - 1);
    }
}

/* number of leading bytes of a UTF-8 code point at p (1..4; 1 on a malformed byte) */
static int capm_cplen(const unsigned char *p) {
    unsigned char c = *p;
    if (c < 0x80) return 1;
    if ((c & 0xE0) == 0xC0 && (p[1] & 0xC0) == 0x80) return 2;
    if ((c & 0xF0) == 0xE0 && (p[1] & 0xC0) == 0x80 && (p[2] & 0xC0) == 0x80) return 3;
    if ((c & 0xF8) == 0xF0 && (p[1] & 0xC0) == 0x80 && (p[2] & 0xC0) == 0x80 && (p[3] & 0xC0) == 0x80) return 4;
    return 1;
}

double cap_model_score(const char *text, int tainted, int private, int tier) {
    if (!capm_ready) capm_init();
    if (!text) text = "";

    /* lowercase ASCII copy (Python str.lower() is Unicode-aware; ASCII covers the corpus) */
    size_t tlen = strlen(text);
    char *low = (char *)malloc(tlen + 1);
    if (!low) return 0.0;
    for (size_t i = 0; i < tlen; i++) {
        unsigned char c = (unsigned char)text[i];
        low[i] = (c < 0x80) ? (char)tolower(c) : (char)c;
    }
    low[tlen] = '\0';

    /* per-document term counts, tracked over the touched columns only */
    int *counts = (int *)calloc(CAPM_N, sizeof(int));
    int *touched = (int *)malloc(sizeof(int) * (tlen * 5 + 8));
    int ntouched = 0;
    if (!counts || !touched) { free(low); free(counts); free(touched); return 0.0; }

    /* iterate whitespace-delimited words */
    size_t i = 0;
    while (i < tlen) {
        while (i < tlen && isspace((unsigned char)low[i])) i++;
        if (i >= tlen) break;
        size_t ws = i;
        while (i < tlen && !isspace((unsigned char)low[i])) i++;
        size_t we = i;   /* word is low[ws, we) */

        /* padded word = " " + word + " " ; index code-point boundaries */
        char pad[1024];
        size_t plen = 0;
        pad[plen++] = ' ';
        for (size_t k = ws; k < we && plen < sizeof(pad) - 2; k++) pad[plen++] = low[k];
        pad[plen++] = ' ';
        /* code-point offset table */
        int cpoff[1030];
        int ncp = 0;
        for (size_t k = 0; k < plen; ) {
            if (ncp < (int)(sizeof(cpoff)/sizeof(cpoff[0]))) cpoff[ncp++] = (int)k;
            k += (size_t)capm_cplen((const unsigned char *)pad + k);
        }
        cpoff[ncp] = (int)plen;   /* sentinel end offset */

        /* char_wb n-grams, n = 3..5, over code points, with sklearn's break semantics */
        for (int n = 3; n <= 5; n++) {
            int off = 0;
            int end = (n < ncp) ? n : ncp;
            {
                int a = cpoff[off], b = cpoff[end];
                int idx = capm_lookup(pad + a, (size_t)(b - a));
                if (idx >= 0) { if (counts[idx]++ == 0) touched[ntouched++] = idx; }
            }
            while (off + n < ncp) {
                off++;
                int a = cpoff[off], b = cpoff[off + n];
                int idx = capm_lookup(pad + a, (size_t)(b - a));
                if (idx >= 0) { if (counts[idx]++ == 0) touched[ntouched++] = idx; }
            }
            if (off == 0) break;   /* word shorter than n: whole word emitted once, stop */
        }
    }

    /* text block: value_j = tf_j*idf_j ; L2-normalize ; dotted with coef (=W/idf*idf) */
    double dot = 0.0, nrm2 = 0.0;
    for (int t = 0; t < ntouched; t++) {
        int idx = touched[t];
        double tf = (double)counts[idx];
        double val = tf * (double)CAPM_IDF[idx];
        dot  += (double)CAPM_W[idx] * tf;   /* W = coef*idf, so W*tf = coef*(tf*idf) */
        nrm2 += val * val;
        counts[idx] = 0;
    }
    double score = CAPM_INTERCEPT
                 + CAPM_COEF_TAINTED * (double)(tainted ? 1 : 0)
                 + CAPM_COEF_PRIVATE * (double)(private ? 1 : 0)
                 + CAPM_COEF_TIER    * (double)tier;
    if (nrm2 > 0.0) score += dot / sqrt(nrm2);

    free(low); free(counts); free(touched);
    return 1.0 / (1.0 + exp(-score));
}

int cap_model_deny(const char *text, int tainted, int private, int tier) {
    return cap_model_score(text, tainted, private, tier) >= 0.5 ? 1 : 0;
}
""")

    print("emitted %s (%d ngrams) and %s" % (C_OUT, n_text, H_OUT))

    # ─────────────────────── parity verification ───────────────────────
    rows = load_parity_rows(limit=500)
    print("parity sample: %d rows" % len(rows))

    import pandas as pd
    X = pd.DataFrame([{"text": r["text"], "tainted": r["tainted"],
                       "private": r["private"], "tier": r["tier"]} for r in rows])
    py_deny = model.predict(X).astype(int)

    c_deny, c_prob = run_c_harness(rows)

    agree = int((py_deny == np.array(c_deny)).sum())
    rate = agree / len(rows) if rows else 0.0
    print("deny-decision parity (C vs joblib): %d/%d = %.2f%%" % (agree, len(rows), 100.0 * rate))
    # also show probability agreement as a sanity check (decision_function avoids a
    # sklearn version-skew attribute on predict_proba)
    py_prob = 1.0 / (1.0 + np.exp(-model.decision_function(X)))
    max_dp = float(np.max(np.abs(py_prob - np.array(c_prob)))) if rows else 0.0
    print("max |prob_py - prob_c| = %.3e" % max_dp)
    if rate <= 0.99:
        mism = [(rows[i]["text"][:80], int(py_deny[i]), c_deny[i]) for i in range(len(rows))
                if py_deny[i] != c_deny[i]][:8]
        for t, a, b in mism:
            print("  MISMATCH py=%d c=%d | %s" % (a, b, t))
        sys.exit(1)
    print("PARITY OK (>99%%)")


def load_parity_rows(limit=500):
    """Pull a mixed sample from the adversarial passes (security-correct labels)."""
    data = os.path.join(REPO, "data", "cap_classifier")
    rows = []
    for path in sorted(glob.glob(os.path.join(data, "passes", "pass0*.jsonl"))):
        with open(path) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                except Exception:
                    continue
                inp = r.get("input", "")
                if not isinstance(inp, str):
                    inp = json.dumps(inp)
                pt = r.get("pre_taint")
                pt = pt if isinstance(pt, dict) else {}
                rows.append({
                    "text": f"{r.get('tool','')} {inp}",
                    "tainted": int(bool(pt.get("untrusted", r.get("pre_taint", 1) if not isinstance(r.get("pre_taint"), dict) else 1))),
                    "private": int(bool(pt.get("private", r.get("pre_private", 1)))),
                    "tier": _tier_code(r.get("tier")) if isinstance(r.get("tier"), str) else int(r.get("tier") or 1),
                })
    # also fold in obfuscated exfil / LAN from the adversarial suite generators
    try:
        sys.path.insert(0, HERE)
        import adversarial_suite as asuite
        import random
        random.seed(3)
        for _ in range(150):
            tool, base = random.choice(asuite.EXFIL_BASES)
            cmd = asuite.random_mutate(base, k=random.randint(1, 5))
            rows.append({"text": f"{tool} {cmd}", "tainted": 1, "private": 1, "tier": 2})
        for _ in range(80):
            tool, base = random.choice(asuite.LAN_BASES)
            cmd = asuite.random_mutate(base, k=random.randint(0, 4))
            rows.append({"text": f"{tool} {cmd}", "tainted": 1, "private": 1, "tier": 2})
    except Exception as e:  # pragma: no cover
        print("  (adversarial-suite augmentation skipped: %s)" % e)
    # cap to `limit`, keep a spread
    if len(rows) > limit:
        step = len(rows) / limit
        rows = [rows[int(k * step)] for k in range(limit)]
    return rows


def run_c_harness(rows):
    """Compile a tiny C driver around cap_model.c and score every row."""
    driver = r"""
#include "cap_model.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main(void) {
    static char line[1 << 16];
    while (fgets(line, sizeof(line), stdin)) {
        /* format: tainted \t private \t tier \t text(rest, may contain tabs) */
        char *p = line;
        int tainted = (int)strtol(p, &p, 10); p++;
        int private = (int)strtol(p, &p, 10); p++;
        int tier    = (int)strtol(p, &p, 10); p++;
        size_t n = strlen(p);
        if (n && p[n-1] == '\n') p[n-1] = '\0';
        double s = cap_model_score(p, tainted, private, tier);
        printf("%d\t%.9f\n", s >= 0.5 ? 1 : 0, s);
    }
    return 0;
}
"""
    tmpd = tempfile.mkdtemp(prefix="capm_")
    drv = os.path.join(tmpd, "drv.c")
    with open(drv, "w") as fh:
        fh.write(driver)
    binp = os.path.join(tmpd, "drv")
    cc = os.environ.get("CC", "cc")
    subprocess.run([cc, "-O2", "-std=c11", "-I", os.path.join(REPO, "include"),
                    drv, C_OUT, "-lm", "-o", binp], check=True)
    # feed rows; text must be single-line — replace embedded newlines
    inp = "".join("%d\t%d\t%d\t%s\n" % (r["tainted"], r["private"], r["tier"],
                                        r["text"].replace("\n", " ").replace("\r", " "))
                  for r in rows)
    out = subprocess.run([binp], input=inp, capture_output=True, text=True, check=True).stdout
    deny, prob = [], []
    for ln in out.splitlines():
        a, b = ln.split("\t")
        deny.append(int(a))
        prob.append(float(b))
    return deny, prob


if __name__ == "__main__":
    main()
