#!/usr/bin/env python3
"""Bake the Distributed Systems wordmark into an RLE coverage header.

Usage: bake_banner_mask.py <logo.png> <out_header.h> [target_width]

Uses macOS `sips` to resize + convert to BMP, then parses the BMP with the
stdlib and emits a run-length-encoded 8-bit coverage mask (white-on-black
luminance) consumed by src/kitty_banner.c.
"""
import struct
import subprocess
import sys
import tempfile
import os


def bake(src, out_path, target_w):
    with tempfile.TemporaryDirectory() as td:
        # Probe source dimensions.
        probe = subprocess.run(
            ["sips", "-g", "pixelWidth", "-g", "pixelHeight", src],
            capture_output=True, text=True, check=True).stdout
        dims = {}
        for line in probe.splitlines():
            line = line.strip()
            for key in ("pixelWidth", "pixelHeight"):
                if line.startswith(key + ":"):
                    dims[key] = int(line.split(":")[1])
        sw, sh = dims["pixelWidth"], dims["pixelHeight"]
        target_h = max(1, round(sh * target_w / sw))

        bmp = os.path.join(td, "mask.bmp")
        subprocess.run(
            ["sips", "-z", str(target_h), str(target_w),
             "-s", "format", "bmp", src, "--out", bmp],
            capture_output=True, check=True)

        data = open(bmp, "rb").read()
        if data[:2] != b"BM":
            raise SystemExit("sips did not produce a BMP")
        pix_off = struct.unpack_from("<I", data, 10)[0]
        hdr_size = struct.unpack_from("<I", data, 14)[0]
        w, h = struct.unpack_from("<ii", data, 18)
        bpp = struct.unpack_from("<H", data, 28)[0]
        if hdr_size < 40 or bpp not in (24, 32):
            raise SystemExit(f"unsupported BMP (hdr={hdr_size} bpp={bpp})")
        flipped = h > 0
        h = abs(h)
        stride = ((w * (bpp // 8)) + 3) & ~3
        step = bpp // 8

        cov = bytearray(w * h)
        for y in range(h):
            src_y = (h - 1 - y) if flipped else y
            row = pix_off + src_y * stride
            for x in range(w):
                b = data[row + x * step]
                g = data[row + x * step + 1]
                r = data[row + x * step + 2]
                cov[y * w + x] = (r * 299 + g * 587 + b * 114) // 1000

    # Crop to the wordmark bounding box (+2px pad) so canvas rows aren't
    # spent on the source image's empty margins.
    xs = [x for y in range(h) for x in range(w) if cov[y * w + x] > 16]
    ys = [y for y in range(h) for x in range(w) if cov[y * w + x] > 16]
    if xs:
        x0, x1 = max(0, min(xs) - 2), min(w - 1, max(xs) + 2)
        y0, y1 = max(0, min(ys) - 2), min(h - 1, max(ys) + 2)
        cw, ch = x1 - x0 + 1, y1 - y0 + 1
        cov = bytearray(cov[(y0 + y) * w + x0 + x]
                        for y in range(ch) for x in range(cw))
        w, h = cw, ch

    # Pair RLE: (run 1..255, value). Mostly long 0/255 runs; AA edges are
    # short runs of intermediate values.
    rle = bytearray()
    i, n = 0, len(cov)
    while i < n:
        v = cov[i]
        run = 1
        while run < 255 and i + run < n and cov[i + run] == v:
            run += 1
        rle.append(run)
        rle.append(v)
        i += run

    with open(out_path, "w") as f:
        f.write("/* Generated by scripts/bake_banner_mask.py — do not edit.\n")
        f.write(f" * Source: {os.path.basename(src)} ({sw}x{sh}) -> {w}x{h} coverage mask. */\n")
        f.write("#ifndef DSCO_KITTY_BANNER_MASK_H\n#define DSCO_KITTY_BANNER_MASK_H\n\n")
        f.write(f"#define BANNER_MASK_W {w}\n#define BANNER_MASK_H {h}\n\n")
        f.write("/* Pairs of (run_length, coverage). Expands to BANNER_MASK_W*BANNER_MASK_H bytes. */\n")
        f.write(f"static const unsigned char k_banner_mask_rle[{len(rle)}] = {{\n")
        for off in range(0, len(rle), 20):
            chunk = rle[off:off + 20]
            f.write("    " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n\n#endif /* DSCO_KITTY_BANNER_MASK_H */\n")
    print(f"{out_path}: {w}x{h} mask, {len(rle)} RLE bytes")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        raise SystemExit(__doc__)
    bake(sys.argv[1], sys.argv[2],
         int(sys.argv[3]) if len(sys.argv) > 3 else 720)
