#!/usr/bin/env python3
"""bake_data.py — encrypting pizza-box compiler.

Converts every file in data/ into an encrypted .c translation unit under
src/generated/, so `strings`/`grep` on the shipped binary reveal nothing of the
baked config. Blobs are decrypted lazily at runtime by src/embedded_data.c via
the same HMAC-SHA256-CTR keystream (key reconstructed from scattered shares).

Outputs:
  src/generated/embedded_<sym>.c    — encrypted byte array + plaintext length
  src/generated/embedded_key.gen.h  — 4 XOR shares of the key + nonce (gitignored)
  include/embedded_data_registry.h  — extern decls + registry table (IMPL-gated)

The key is persisted in build/.embed_key so incremental rebuilds stay coherent
(mixing blobs encrypted under different keys would corrupt them). Delete that
file (or `make clean`) to roll the key, which forces a full re-bake.

Usage: bake_data.py [data_dir] [out_c_dir] [out_h_dir] [key_file]
"""
import hashlib
import hmac
import os
import re
import struct
import sys

data_dir = sys.argv[1] if len(sys.argv) > 1 else "data"
out_c_dir = sys.argv[2] if len(sys.argv) > 2 else "src/generated"
out_h_dir = sys.argv[3] if len(sys.argv) > 3 else "include"
key_file = sys.argv[4] if len(sys.argv) > 4 else "build/.embed_key"

os.makedirs(out_c_dir, exist_ok=True)
os.makedirs(os.path.dirname(key_file) or ".", exist_ok=True)


def keystream_xor(key: bytes, nonce: bytes, data: bytes) -> bytes:
    """HMAC-SHA256-CTR keystream XOR. Must match ks_xor() in embedded_data.c."""
    out = bytearray(data)
    off, ctr = 0, 0
    while off < len(out):
        block = hmac.new(key, nonce + struct.pack("<Q", ctr), hashlib.sha256).digest()
        n = min(32, len(out) - off)
        for i in range(n):
            out[off + i] ^= block[i]
        off += n
        ctr += 1
    return bytes(out)


# ── Key material: reuse if present, else generate (and force full re-bake) ──
force_all = False
if os.path.exists(key_file):
    with open(key_file, "rb") as fh:
        blob = fh.read()
    key, nonce = blob[:32], blob[32:48]
    if len(key) != 32 or len(nonce) != 16:
        key, nonce, force_all = os.urandom(32), os.urandom(16), True
else:
    key, nonce, force_all = os.urandom(32), os.urandom(16), True
if force_all:
    with open(key_file, "wb") as fh:
        fh.write(key + nonce)
    try:
        os.chmod(key_file, 0o600)
    except OSError:
        pass

# Four random XOR shares that reconstruct the key: s0^s1^s2^s3 == key.
shares = [os.urandom(32) for _ in range(3)]
last = bytes(key[i] ^ shares[0][i] ^ shares[1][i] ^ shares[2][i] for i in range(32))
shares.append(last)


def sym_name(filename: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", filename)
    return s


def c_bytes(b: bytes) -> str:
    lines, row = [], []
    for i, byte in enumerate(b):
        row.append("0x%02x" % byte)
        if len(row) == 12:
            lines.append("  " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ",".join(row) + ",")
    return "\n".join(lines)


entries = []  # (csym, filename)
for filename in sorted(os.listdir(data_dir)):
    filepath = os.path.join(data_dir, filename)
    if not os.path.isfile(filepath) or filename.startswith("."):
        continue
    sym = sym_name(filename)
    csym = "dsco_data_%s" % sym
    out_c = os.path.join(out_c_dir, "embedded_%s.c" % sym)
    entries.append((csym, filename))

    if (not force_all and os.path.exists(out_c)
            and os.path.getmtime(out_c) >= os.path.getmtime(filepath)):
        print("  [bake] up-to-date: %s" % filename)
        continue

    print("  [bake] encrypting: %s -> %s" % (filename, out_c))
    with open(filepath, "rb") as fh:
        plaintext = fh.read()
    ciphertext = keystream_xor(key, nonce, plaintext)
    with open(out_c, "w") as fh:
        fh.write("/* AUTO-GENERATED by scripts/bake_data.py — do not edit.\n")
        fh.write(" * Source: %s (encrypted at rest; decrypted lazily at runtime)\n */\n" % filepath)
        fh.write("#include <stddef.h>\n\n")
        fh.write("const unsigned char %s[] = {\n%s\n};\n\n" % (csym, c_bytes(ciphertext)))
        fh.write("const size_t %s_len = %d;\n" % (csym, len(plaintext)))


# ── Scattered key header (gitignored) ──
def c_arr(name, b):
    return "static const uint8_t %s[%d] = {\n%s\n};\n" % (name, len(b), c_bytes(b))


key_h = os.path.join(out_h_dir, "embedded_key.gen.h")
with open(key_h, "w") as fh:
    fh.write("/* AUTO-GENERATED by scripts/bake_data.py — do not edit. Secret; gitignored. */\n")
    fh.write("#ifndef DSCO_EMBEDDED_KEY_GEN_H\n#define DSCO_EMBEDDED_KEY_GEN_H\n#include <stdint.h>\n\n")
    for i, sh in enumerate(shares):
        fh.write(c_arr("DSCO_EMB_S%d" % i, sh))
    fh.write(c_arr("DSCO_EMB_NONCE", nonce))
    fh.write("\n#endif /* DSCO_EMBEDDED_KEY_GEN_H */\n")

# ── Registry header ──
registry = os.path.join(out_h_dir, "embedded_data_registry.h")
with open(registry, "w") as fh:
    fh.write("/* AUTO-GENERATED by scripts/bake_data.py — do not edit.\n")
    fh.write(" * embedded_data_get(name, &len) returns the DECRYPTED blob (impl: embedded_data.c). */\n")
    fh.write("#ifndef DSCO_EMBEDDED_DATA_REGISTRY_H\n#define DSCO_EMBEDDED_DATA_REGISTRY_H\n\n")
    fh.write("#include <stddef.h>\n\n")
    for csym, _ in entries:
        fh.write("extern const unsigned char %s[];\n" % csym)
        fh.write("extern const size_t        %s_len;\n" % csym)
    fh.write("\nconst unsigned char *embedded_data_get(const char *name, size_t *out_len);\n\n")
    fh.write("#ifdef DSCO_EMBEDDED_DATA_IMPL\n")
    fh.write("typedef struct { const char *name; const unsigned char *data; const size_t *len; }\n")
    fh.write("        dsco_embedded_entry_t;\n")
    fh.write("static const dsco_embedded_entry_t dsco_embedded_registry_table[] = {\n")
    for csym, name in entries:
        fh.write('    { "%s", %s, &%s_len },\n' % (name, csym, csym))
    fh.write("    { NULL, NULL, NULL }\n};\n")
    fh.write("#endif /* DSCO_EMBEDDED_DATA_IMPL */\n\n")
    fh.write("#endif /* DSCO_EMBEDDED_DATA_REGISTRY_H */\n")

print("  [bake] registry -> %s (%d entries, encrypted)" % (registry, len(entries)))
