#!/bin/bash
# bake_data.sh — pizza box compiler
# Converts every file in data/ into a .c translation unit in src/generated/.
# Also generates include/embedded_data_registry.h with the full manifest.
#
# Output per file data/foo.bar:
#   src/generated/embedded_foo_bar.c   — const byte array + len symbol
#   include/embedded_data_registry.h   — registry of all known blobs (regen each build)
#
# Usage: scripts/bake_data.sh [data_dir] [out_c_dir] [out_h_dir]
#
set -euo pipefail

DATA_DIR="${1:-data}"
OUT_C_DIR="${2:-src/generated}"
OUT_H_DIR="${3:-include}"
REGISTRY="$OUT_H_DIR/embedded_data_registry.h"

mkdir -p "$OUT_C_DIR"

ENTRIES=()   # accumulate for registry

for filepath in "$DATA_DIR"/*; do
    [ -f "$filepath" ] || continue
    filename=$(basename "$filepath")

    # Symbol-safe name: foo.bar → foo_bar
    sym=$(echo "$filename" | tr '.-' '__' | tr '/' '_' | sed 's/[^a-zA-Z0-9_]/_/g')
    csym="dsco_data_${sym}"
    out_c="$OUT_C_DIR/embedded_${sym}.c"

    # Skip regeneration if .c is newer than source file (incremental)
    if [ -f "$out_c" ] && [ "$out_c" -nt "$filepath" ]; then
        echo "  [bake] up-to-date: $filename"
        ENTRIES+=("$csym|$filename")
        continue
    fi

    echo "  [bake] baking: $filename -> $out_c"

    # Write the .c file
    cat > "$out_c" << EOF
/* AUTO-GENERATED by scripts/bake_data.sh — do not edit.
 * Source: $filepath
 * Baked:  $(date -u +"%Y-%m-%dT%H:%M:%SZ")
 */
#include <stddef.h>

EOF

    # xxd -i produces the array body; we strip the variable declarations
    # and emit our own with the canonical symbol name
    printf 'const unsigned char %s[] = {\n' "$csym" >> "$out_c"
    xxd -i "$filepath" | grep -v '^unsigned\|^};' | grep -v 'unsigned int' >> "$out_c"
    printf '};\n\n' >> "$out_c"
    printf 'const size_t %s_len = %s;\n' "$csym" "$(wc -c < "$filepath" | tr -d ' ')" >> "$out_c"

    ENTRIES+=("$csym|$filename")
done

# Regenerate the registry header every time (fast, just text)
cat > "$REGISTRY" << 'HEADER'
/* AUTO-GENERATED by scripts/bake_data.sh — do not edit.
 * Include this header to access the embedded data registry.
 * Use embedded_data_get(name, &len) to retrieve any blob by original filename.
 */
#ifndef DSCO_EMBEDDED_DATA_REGISTRY_H
#define DSCO_EMBEDDED_DATA_REGISTRY_H

#include <stddef.h>
#include <string.h>

HEADER

# Emit extern decls
for entry in "${ENTRIES[@]}"; do
    sym="${entry%%|*}"
    cat >> "$REGISTRY" << EOF
extern const unsigned char ${sym}[];
extern const size_t        ${sym}_len;
EOF
done

# Emit the registry table + get() function
cat >> "$REGISTRY" << 'FOOTER'

typedef struct {
    const char          *name;
    const unsigned char *data;
    const size_t        *len;
} dsco_embedded_entry_t;

static inline const unsigned char *
embedded_data_get(const char *name, size_t *out_len) {
    static const dsco_embedded_entry_t _registry[] = {
FOOTER

for entry in "${ENTRIES[@]}"; do
    sym="${entry%%|*}"
    name="${entry##*|}"
    printf '        { "%s", %s, &%s_len },\n' "$name" "$sym" "$sym" >> "$REGISTRY"
done

cat >> "$REGISTRY" << 'TAIL'
        { NULL, NULL, NULL }
    };
    for (int _i = 0; _registry[_i].name; _i++) {
        if (strcmp(_registry[_i].name, name) == 0) {
            if (out_len) *out_len = *_registry[_i].len;
            return _registry[_i].data;
        }
    }
    if (out_len) *out_len = 0;
    return NULL;
}

#endif /* DSCO_EMBEDDED_DATA_REGISTRY_H */
TAIL

echo "  [bake] registry -> $REGISTRY (${#ENTRIES[@]} entries)"
