#!/usr/bin/env python3
"""Broad paired QA benchmark for local Entropix-inspired selection."""
import argparse, importlib.util, json, re, sys, time
from pathlib import Path
spec=importlib.util.spec_from_file_location('ep',Path(__file__).with_name('entropix_proxy.py')); ep=importlib.util.module_from_spec(spec); spec.loader.exec_module(ep)
# Short-answer cases with explicit aliases; deliberately spans factual, science,
# humanities, logic, quantitative, CS, and ambiguity-resistant common knowledge.
CASES=[
('geo','Capital of Australia? Reply only with the city.',['canberra']),('geo','Capital of Kazakhstan? Reply only with the city.',['astana']),('geo','Which river flows through Budapest? Reply only with its English name.',['danube','danube river']),('geo','Largest country in Africa by area? Reply only with the country.',['algeria']),('geo','Mount Kilimanjaro is in which country? Reply only with the country.',['tanzania']),
('history','In what year did the Berlin Wall fall? Reply only with the year.',['1989']),('history','Who was the first emperor of Rome? Reply only with the name.',['augustus','caesar augustus','augustus caesar']),('history','Which treaty ended World War I between Germany and the Allies? Reply only with its common name.',['treaty of versailles','versailles treaty']),('history','Who led the Haitian Revolution and became governor-general for life? Reply only with the name.',['toussaint louverture','francois dominique toussaint louverture']),('history','The Meiji Restoration began in what year? Reply only with the year.',['1868']),
('science','Chemical symbol for tungsten? Reply only with the symbol.',['w']),('science','SI unit of electric resistance? Reply only with the unit.',['ohm','ohms']),('science','Which planet has the shortest day? Reply only with the planet.',['jupiter']),('science','What particle mediates the electromagnetic force? Reply only with the particle.',['photon']),('science','What is the most abundant gas in Earth atmosphere? Reply only with the gas.',['nitrogen','n2']),
('biology','Organelle primarily responsible for ATP production in eukaryotic cells? Reply only with the organelle.',['mitochondrion','mitochondria']),('biology','How many pairs of chromosomes do typical human somatic cells have? Reply only with the integer.',['23']),('biology','Which enzyme unwinds DNA at the replication fork? Reply only with the enzyme.',['helicase','dna helicase']),('biology','Blood type called the universal red-cell donor? Reply only with the type.',['o negative','o-']),('biology','The genetic code is read in groups of how many nucleotides? Reply only with the integer.',['3','three']),
('literature','Who wrote One Hundred Years of Solitude? Reply only with the author.',['gabriel garcia marquez','gabriel garcía márquez']),('literature','Who wrote The Master and Margarita? Reply only with the author.',['mikhail bulgakov']),('literature','In Hamlet, who is Ophelia father? Reply only with the name.',['polonius']),('literature','Which novel begins with Call me Ishmael? Reply only with the title.',['moby dick','moby-dick']),('literature','Who wrote Things Fall Apart? Reply only with the author.',['chinua achebe']),
('philosophy','Who wrote Critique of Pure Reason? Reply only with the philosopher.',['immanuel kant','kant']),('philosophy','The allegory of the cave appears in which Platonic work? Reply only with the title.',['the republic','republic']),('philosophy','Who formulated the categorical imperative? Reply only with the philosopher.',['immanuel kant','kant']),('philosophy','Cogito ergo sum is associated with whom? Reply only with the philosopher.',['rene descartes','rené descartes','descartes']),('philosophy','Who wrote Being and Time? Reply only with the philosopher.',['martin heidegger','heidegger']),
('economics','What does GDP stand for? Reply only with the expansion.',['gross domestic product']),('economics','A sustained general increase in prices is called what? Reply only with the term.',['inflation']),('economics','Who wrote The General Theory of Employment, Interest and Money? Reply only with the author.',['john maynard keynes','keynes']),('economics','Opportunity cost is the value of what? Reply with only: next best alternative',['next best alternative']),('economics','If nominal interest is 7% and inflation is 3%, approximate real interest rate? Reply only with the percentage.',['4%','4 percent','4']),
('cs','Time complexity of binary search in a sorted array? Reply only in Big-O notation.',['o(log n)','ologn']),('cs','Which data structure uses FIFO order? Reply only with the structure.',['queue']),('cs','What consistency theorem is abbreviated CAP? Reply only with the three properties.',['consistency availability partition tolerance']),('cs','In Git, which command creates a new branch and switches to it in traditional syntax? Reply only with the command.',['git checkout -b']),('cs','Default port for HTTPS? Reply only with the integer.',['443']),
('math','What is 17 choose 2? Reply only with the integer.',['136']),('math','What is the derivative of x^3? Reply only with the expression.',['3x^2','3x²']),('math','A triangle has angles 35 and 65 degrees. Third angle? Reply only with the integer.',['80']),('math','What is 1440 divided by 32? Reply only with the integer.',['45']),('math','What is the remainder when 2^20 is divided by 7? Reply only with the integer.',['4']),
('logic','All A are B. No B are C. Can any A be C? Reply only yes or no.',['no']),('logic','Some poets are scientists. All scientists are curious. Does it follow that some poets are curious? Reply only yes or no.',['yes']),('logic','If P implies Q and Q is false, must P be false? Reply only yes or no.',['yes']),('logic','If either Alice or Bob won, and Alice did not win, who won? Reply only with the name.',['bob']),('logic','A statement and its negation cannot both be true under which classical principle? Reply only with the principle.',['law of non contradiction','principle of non contradiction','non contradiction']),
('medicine','Deficiency of which vitamin causes scurvy? Reply only with the vitamin.',['vitamin c','c']),('medicine','Which organ produces insulin? Reply only with the organ.',['pancreas']),('medicine','Normal adult resting heart rate is commonly expressed in what unit? Reply only with the unit.',['beats per minute','bpm']),('medicine','The functional unit of the kidney is called what? Reply only with the term.',['nephron']),('medicine','Which blood cells primarily carry oxygen? Reply only with the cell type.',['red blood cells','erythrocytes','red blood cell']),
('law','What is the highest court in the United States? Reply only with the court name.',['supreme court','united states supreme court','us supreme court']),('law','A written false statement harming reputation is called what? Reply only with the term.',['libel']),('law','The burden of proof in most civil cases is called what? Reply only with the standard.',['preponderance of the evidence','preponderance of evidence']),('law','Latin term meaning a guilty mind? Reply only with the term.',['mens rea']),('law','What doctrine requires courts to follow precedent? Reply only with the Latin term.',['stare decisis']),
]
def norm(s): return re.sub(r'[^a-z0-9]+','',s.lower().replace('²','^2'))
def ok(s,aliases): return any(norm(s)==norm(a) for a in aliases)
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--model',default='qwen35-27b-dense'); ap.add_argument('-n',type=int,default=5); ap.add_argument('--temperature',type=float,default=.9); ap.add_argument('--seed',type=int,default=91000); ap.add_argument('--output',required=True); a=ap.parse_args(); rows=[]
 for i,(cat,prompt,gold) in enumerate(CASES):
  msgs=[{'role':'user','content':prompt}]; g=ep.complete('http://127.0.0.1:1234/v1/chat/completions',a.model,msgs,a.seed+i,0,1,80,20); pool=[]
  for j in range(a.n): pool.append(ep.complete('http://127.0.0.1:1234/v1/chat/completions',a.model,msgs,a.seed+10000+i*a.n+j,a.temperature,.95,80,20))
  picks={p:ep.select(pool,p)[0] for p in ('likelihood','low_entropy','consensus')}; r={'i':i,'category':cat,'prompt':prompt,'gold':gold,'greedy':g['text'],'greedy_ok':ok(g['text'],gold),'oracle':any(ok(x['text'],gold) for x in pool),'pool':[x['text'] for x in pool]}
  for p,x in picks.items(): r[p]=x['text']; r[p+'_ok']=ok(x['text'],gold)
  rows.append(r); print(json.dumps(r,ensure_ascii=False),flush=True)
 methods=['greedy','likelihood','low_entropy','consensus']; summary={'total':len(rows),'oracle':sum(r['oracle'] for r in rows)}
 for m in methods: summary[m]=sum(r[m+'_ok'] for r in rows)
 for m in methods[1:]: summary[m+'_fixes']=sum(not r['greedy_ok'] and r[m+'_ok'] for r in rows); summary[m+'_regressions']=sum(r['greedy_ok'] and not r[m+'_ok'] for r in rows)
 cats={};
 for c in sorted(set(r['category'] for r in rows)): cats[c]={m:sum(r[m+'_ok'] for r in rows if r['category']==c) for m in methods}|{'total':sum(r['category']==c for r in rows)}
 out={'config':vars(a),'summary':summary,'categories':cats,'rows':rows}; Path(a.output).write_text(json.dumps(out,ensure_ascii=False,indent=2)); print('FINAL '+json.dumps({'summary':summary,'categories':cats}));
if __name__=='__main__': main()
