#!/usr/bin/env python3
"""Embed reviewed Lingo source; never load a runtime from the caller's cwd."""
from pathlib import Path
import re
import sys
source_path = Path(sys.argv[1])
source = source_path.read_bytes()
target = Path(sys.argv[2])
symbol = sys.argv[3] if len(sys.argv) > 3 else 'lingo_runtime'
if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', symbol):
    raise SystemExit('invalid C symbol')
text = f'/* Generated by scripts/embed_lingo.py; edit {source_path.as_posix()}. */\n'
text += f'static const unsigned char {symbol}[] = {{\n'
text += '\n'.join(','.join(str(b) for b in source[i:i+24]) + ','
                  for i in range(0, len(source), 24))
text += '\n0};\n'
if not target.exists() or target.read_text() != text:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
