#!/usr/bin/env python3
"""Generate a minimal Ninja wrapper that delegates to Make.
This preserves the Makefile as source of truth while satisfying ninja-file workflows.
"""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
out = ROOT / "build.ninja"
out.write_text("""# Generated by scripts/gen_ninja.py. Makefile remains source of truth.
rule make
  command = make $target
  description = MAKE $target

build dsco: make
  target = dsco

build test: make
  target = test

build docs-check: make
  target = docs-check

default dsco
""")
print(f"wrote {out}")
