#!/usr/bin/env python3
"""Generate a tracked-file coverage manifest for the repository."""
from __future__ import annotations

import argparse
import subprocess
import sys
from collections import defaultdict
from pathlib import Path


CATEGORY_ORDER = [
    "Root project files",
    "Repository policy and CI",
    "Documentation",
    "Runtime source and headers",
    "Tests",
    "Scripts and tooling",
    "Generated data assets",
    "Provider metadata",
    "Web surface",
    "Packaging and distribution",
    "Demos",
    "Vendored and compatibility code",
    "Other tracked files",
]


def run_git_ls_files(root: Path) -> list[str]:
    proc = subprocess.run(
        ["git", "-C", str(root), "ls-files"],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or "git ls-files failed")
    return [line for line in proc.stdout.splitlines() if line]


def classify(path: str) -> str:
    if "/" not in path:
        return "Root project files"
    if path.startswith(".github/") or path.startswith(".") or path == "CODEOWNERS":
        return "Repository policy and CI"
    if path.startswith("docs/"):
        return "Documentation"
    if path.startswith("src/") or path.startswith("include/") or path == "dsc.c":
        return "Runtime source and headers"
    if path.startswith("tests/"):
        return "Tests"
    if path.startswith("scripts/") or path == "face_capture.py":
        return "Scripts and tooling"
    if path.startswith("data/"):
        return "Generated data assets"
    if path.startswith("provider_metadata/"):
        return "Provider metadata"
    if path.startswith("web/"):
        return "Web surface"
    if path.startswith("npm/") or path.startswith("Formula/"):
        return "Packaging and distribution"
    if path.startswith("demos/"):
        return "Demos"
    if path.startswith("vendor/") or path.startswith("gsl/"):
        return "Vendored and compatibility code"
    return "Other tracked files"


def build_markdown(root: Path, out_rel: str) -> str:
    files = set(run_git_ls_files(root))
    files.add(out_rel)
    files.add("docs/EXTERNAL_TOOL_CATALOG.md")
    files.add("scripts/gen_external_tool_catalog.py")
    files.add("scripts/gen_repo_coverage.py")

    by_category: dict[str, list[str]] = defaultdict(list)
    for path in sorted(files):
        by_category[classify(path)].append(path)

    lines: list[str] = [
        "# Repository Coverage Manifest",
        "",
        "Generated by `scripts/gen_repo_coverage.py`. Do not hand-edit; run `make docs` after adding, removing, or moving tracked repository files.",
        "",
        "This manifest is generated from `git ls-files` plus the coverage generator/output paths, so it covers committed source, docs, tests, metadata, packaging, vendored code, and CI policy without indexing ignored local scratch files.",
        "",
        "## Summary",
        "",
        f"- Total covered files: {sum(len(v) for v in by_category.values())}",
        "",
        "| Category | Files |",
        "|---|---:|",
    ]

    for category in CATEGORY_ORDER:
        if by_category.get(category):
            lines.append(f"| {category} | {len(by_category[category])} |")

    lines.extend(
        [
            "",
            "## Generated Coverage",
            "",
            "- `docs/API_REFERENCE.md` is generated from `include/**/*.h`.",
            "- `docs/TOOL_CATALOG.md` is generated from `src/tools.c` built-in tool registrations.",
            "- `docs/CONSTANTS_ENV_INDEX.md` and `data/constants_env_index.json` are generated from C constants and env-var usage.",
            "- This file is generated from the repository file set and keeps broad repo-surface coverage visible in docs review.",
            "",
            "## Covered Files",
            "",
        ]
    )

    for category in CATEGORY_ORDER:
        paths = by_category.get(category)
        if not paths:
            continue
        lines.append(f"### {category}")
        lines.append("")
        for path in paths:
            lines.append(f"- `{path}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="repository root")
    parser.add_argument("--out", default="docs/REPO_COVERAGE.md", help="manifest output path")
    parser.add_argument("--check", action="store_true", help="verify the manifest without rewriting it")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    out_path = root / args.out
    out_rel = out_path.relative_to(root).as_posix()

    try:
        generated = build_markdown(root, out_rel)
    except RuntimeError as exc:
        print(f"repo coverage failed: {exc}", file=sys.stderr)
        return 1

    if args.check:
        current = out_path.read_text(errors="ignore") if out_path.exists() else ""
        if current != generated:
            print(
                "docs drift: repository coverage manifest is out of date. Run "
                "python3 scripts/gen_repo_coverage.py --root .",
                file=sys.stderr,
            )
            return 1
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generated)
    print(f"wrote {out_rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
