#!/usr/bin/env python3
"""gen_cstring_key.py — generate the key material for __cstring encryption.

Emits:
  include/cstring_key.gen.h  — 4 XOR shares of the key + nonce (C, gitignored)
  build/.cstring_key         — raw key||nonce for scripts/encrypt_cstring.py

The C constructor (src/cstring_unlock.c) and the post-link encryptor share this
key and the HMAC-SHA256-CTR keystream. Regenerated per build via `make harden-max`.
"""
import os
import sys

out_h = sys.argv[1] if len(sys.argv) > 1 else "include/cstring_key.gen.h"
key_file = sys.argv[2] if len(sys.argv) > 2 else "build/.cstring_key"

os.makedirs(os.path.dirname(out_h) or ".", exist_ok=True)
os.makedirs(os.path.dirname(key_file) or ".", exist_ok=True)

key = os.urandom(32)
nonce = os.urandom(16)
with open(key_file, "wb") as fh:
    fh.write(key + nonce)
try:
    os.chmod(key_file, 0o600)
except OSError:
    pass

shares = [os.urandom(32) for _ in range(3)]
last = bytes(key[i] ^ shares[0][i] ^ shares[1][i] ^ shares[2][i] for i in range(32))
shares.append(last)


def c_arr(name, b):
    body = ",".join("0x%02x" % x for x in b)
    return "static const uint8_t %s[%d] = {%s};\n" % (name, len(b), body)


with open(out_h, "w") as fh:
    fh.write("/* AUTO-GENERATED by scripts/gen_cstring_key.py — secret; gitignored. */\n")
    fh.write("#ifndef DSCO_CSTRING_KEY_GEN_H\n#define DSCO_CSTRING_KEY_GEN_H\n#include <stdint.h>\n")
    for i, sh in enumerate(shares):
        fh.write(c_arr("CSTR_S%d" % i, sh))
    fh.write(c_arr("CSTR_NONCE", nonce))
    fh.write("#endif\n")

print("  [cstring] key -> %s (+ %s)" % (out_h, key_file))
