#ifndef DSCO_CAP_MODEL_H
#define DSCO_CAP_MODEL_H

/* AUTO-GENERATED by environments/capability_gate/ml/export_to_c.py — DO NOT EDIT.
 * Pure-C compilation of the learned LR capability-gate advisor
 * (advisor_model_v2.joblib): char_wb(3,5) tf-idf + numeric -> logistic regression. */

#ifdef __cplusplus
extern "C" {
#endif

/* Sigmoid probability that the tool call should be DENIED (exfil-risk), in [0,1].
 * `text` is "<tool> <input_json>"; tainted/private are 0/1 session flags; tier is
 * 0=untrusted,1=standard,2=trusted. Reproduces the sklearn pipeline bit-for-bit. */
double cap_model_score(const char *text, int tainted, int private, int tier);

/* 1 iff cap_model_score(...) >= 0.5. */
int cap_model_deny(const char *text, int tainted, int private, int tier);

#ifdef __cplusplus
}
#endif

#endif /* DSCO_CAP_MODEL_H */
