/* AUTO-GENERATED by scripts/bake_data.py — do not edit.
 * embedded_data_get(name, &len) returns the DECRYPTED blob (impl: embedded_data.c). */
#ifndef DSCO_EMBEDDED_DATA_REGISTRY_H
#define DSCO_EMBEDDED_DATA_REGISTRY_H

#include <stddef.h>

extern const unsigned char dsco_data_constants_env_index_json[];
extern const size_t        dsco_data_constants_env_index_json_len;
extern const unsigned char dsco_data_dsco_secrets_txt[];
extern const size_t        dsco_data_dsco_secrets_txt_len;
extern const unsigned char dsco_data_tool_embeddings_bin[];
extern const size_t        dsco_data_tool_embeddings_bin_len;

const unsigned char *embedded_data_get(const char *name, size_t *out_len);

#ifdef DSCO_EMBEDDED_DATA_IMPL
typedef struct { const char *name; const unsigned char *data; const size_t *len; }
        dsco_embedded_entry_t;
static const dsco_embedded_entry_t dsco_embedded_registry_table[] = {
    { "constants_env_index.json", dsco_data_constants_env_index_json, &dsco_data_constants_env_index_json_len },
    { "dsco_secrets.txt", dsco_data_dsco_secrets_txt, &dsco_data_dsco_secrets_txt_len },
    { "tool_embeddings.bin", dsco_data_tool_embeddings_bin, &dsco_data_tool_embeddings_bin_len },
    { NULL, NULL, NULL }
};
#endif /* DSCO_EMBEDDED_DATA_IMPL */

#endif /* DSCO_EMBEDDED_DATA_REGISTRY_H */
