/* AUTO-GENERATED by scripts/bake_data.sh — do not edit.
 * Include this header to access the embedded data registry.
 * Use embedded_data_get(name, &len) to retrieve any blob by original filename.
 */
#ifndef DSCO_EMBEDDED_DATA_REGISTRY_H
#define DSCO_EMBEDDED_DATA_REGISTRY_H

#include <stddef.h>
#include <string.h>

extern const unsigned char dsco_data_tool_embeddings_bin[];
extern const size_t        dsco_data_tool_embeddings_bin_len;

typedef struct {
    const char          *name;
    const unsigned char *data;
    const size_t        *len;
} dsco_embedded_entry_t;

static inline const unsigned char *
embedded_data_get(const char *name, size_t *out_len) {
    static const dsco_embedded_entry_t _registry[] = {
        { "tool_embeddings.bin", dsco_data_tool_embeddings_bin, &dsco_data_tool_embeddings_bin_len },
        { NULL, NULL, NULL }
    };
    for (int _i = 0; _registry[_i].name; _i++) {
        if (strcmp(_registry[_i].name, name) == 0) {
            if (out_len) *out_len = *_registry[_i].len;
            return _registry[_i].data;
        }
    }
    if (out_len) *out_len = 0;
    return NULL;
}

#endif /* DSCO_EMBEDDED_DATA_REGISTRY_H */
